### ISSUE TITLE
nested TabBarNavigator in StackNavigator cause blank screens

### ISSUE THREAD

**Issue by Under-Warz** [react-navigation/react-navigation-redux-helpers#10]
### Current Behavior

When I navigate between Tabbar screen, the initial screen is loaded properly, mais the other are blank (no render method call)

Here is a demo to reproduce the bug WITH REDUX : https://snack.expo.io/@lmenu/sample-for-tabbar-bug
Here is the same demo WITHOUT REDUX without the bug : https://snack.expo.io/@lmenu/sample-for-tabbar-bug-without-redux

### How to reproduce

I red that adding param `swipeEnabled: false, animationEnabled: false, lazy: true` solve the problem. I did it but have no effect. But if I put `swipeEnabled: true` or `animationEnabled: true`, everything is OK.

Here is the structure of my navigation routes.

- Root StackNavigator (mode modal)
 -- Auth StackNavigator
 -- App TabBarNavigator
 ---- Home StackNavigator
 ---- Notif StackNavigator
 ---- ... Other navigators
 -- ... Other modals

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.2.0
| react-native     | 0.50.4
| node             | 9.4.0
| yarn      | 1.3.2

I'm using Redux with the new library package (react-navigation-redux-helpers)

Thank's in advance.

**Comment by brentvatne** [comment]
I posted a workaround in this other thread: https://github.com/react-navigation/react-navigation-redux-helpers/issues/7#issuecomment-368934521

**Comment by Under-Warz** [comment]
@brentvatne If you could read a little more my issue I open for the third time, you could see that the problem is not the same. The issue for #7 loads the tab after tap a second time on it. For my case, even if you tap and tap again the screen is not loaded.

By the way, I've update the snacks with your solution, but the bug persist.

Thx,

**Comment by brentvatne** [comment]
cc @Ashoat

**Comment by LcTwisk** [comment]
I'm having the same issue. The proposed solution in #7 is also not working for me.

**Comment by LcTwisk** [comment]
Just found out that it is still working on `react-navigation`-` v1.0.3`, but it breaks when updating to `v1.1.0` or up

**Comment by hushicai** [comment]
I have temporarily  move to `react-native-tab-navigator`.

Looking forward to the solution.

**Comment by Ashoat** [comment]
Oh my god, this report has *exact* same typo as [#3586](https://github.com/react-navigation/react-navigation/issues/3586).

Guys. The callback you pass to `createReactNavigationReduxMiddleware` has to select the navigation state from your Redux store. It can't select an undefined property.

I've considered warning in the case of an `undefined` property, but having the first action initialize state from `null` is a common Redux pattern (and one `react-navigation` uses).

**Comment by Under-Warz** [comment]
@Ashoat thank's ! It working. It was a typo issue, I was using your exemple state.nav but my reducer is called "navigation" >_<

@hushicai & @LcTwisk  let's try this for you ;)
