### ISSUE TITLE
SwitchNavigator doesn't work with Redux integration outlined in guide

### ISSUE THREAD

**Issue by nextriot** [react-navigation/react-navigation-redux-helpers#18]
Hi.

I'm using the exact Redux Integration outlined in the guide found here: https://reactnavigation.org/docs/redux-integration.html

However, when I export a SwitchNavigator (with a StackNavigator as its initial route) as my default Navigator I'm met with the following error:

`undefined is not an object (evaluating 'prevState.index')`

Here is a Snack reproducing the bug: https://snack.expo.io/Hy643mQtz

![Image of stack trace](https://i.imgur.com/6FADkn8.png)

Any help is much appreciated.

**Comment by julienR2** [comment]
I have the same problem when I update react-navigation from `1.2.1`  to `1.5.2` no sure it comes from `react-navigation-redux-helper`..
I'll try to investigate and see which version breaks it.

**Comment by andreaPortfolio** [comment]
I have the same problem... Any news?

**Comment by mattvick** [comment]
I have the same problem too... Any news?

**Comment by mattvick** [comment]
@nextriot what version of [react-navigation](https://github.com/react-navigation/react-navigation/) and [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers/) are you using?

The react-navigation [ReduxExample](https://github.com/react-navigation/react-navigation/tree/master/examples/ReduxExample), which runs uses the following versions:

react-navigation: **2.0.0-alpha.5**
react-navigation-redux-helpers: **^1.0.0**

**Comment by andreaPortfolio** [comment]
I'm using:
"react-native": "0.52.0",
"react-navigation": "^1.5.1",
"react-navigation-redux-helpers": "^1.0.3"

**Comment by mattvick** [comment]
@nextriot and @andreaPortfolio do you have nested navigations?

**Comment by nextriot** [comment]
@mattvick, thanks for helping. 

Please check the snack (https://snack.expo.io/Hy643mQtz) for any further questions.

The SwitchNavigator is the root, and it has nested StackNavigators.

"react-navigation": "^1.5.1".
"react-navigation-redux-helpers": "^1.0.3".

I don't think 2.0.0-alpha.5 is publicly available. So I don't think that's the issue.

**Comment by mattvick** [comment]
@nextriot take a look at https://snack.expo.io/ByL0C9YFz it runs after setting `const initialState = null`. Can anyone explain what the side effects of setting the initial state to `null` might be?

**Comment by andreaPortfolio** [comment]
I changed my reducer initial state from:

const initialState = AppNavigator.router.getStateForAction(
    AppNavigator.router.getActionForPathAndParams("AuthLoading")
);
to 

const initialState = null;

and now it works!!!

Thank you @mattvick

**Comment by mattvick** [comment]
No worries @andreaPortfolio. Glad I could help. 

It would be great if there was some clear documentation outlining how to set `initialState` for nested navigators. 

Also I'd like to know why the navigation state has to be set in the app and as `initialState`, which seems like setting the same thing in two places

**Comment by pedrobertao** [comment]
This need some clarification. Just setting initialState to null as a solution kinda bugs my mind.

**Comment by mike3run** [comment]
Install react-navigation@next to fix the issue :D

**Comment by Ashoat** [comment]
Is anybody still experiencing this issue?

**Comment by shelldandy** [comment]
Yes but i installed react-navigation@next and the issue was fixed in there

**Comment by Ashoat** [comment]
I think `react-navigation-redux-helpers@1.0.6` should fix this issue for people who are still on `react-navigation@1.x`. If anybody is still experiencing this issue let me know!
