### ISSUE TITLE
Flow errors on react-native 0.54.2

### ISSUE THREAD

**Issue by michel-p** [react-navigation/react-navigation-redux-helpers#19]
Hello,

I am having some flow fails on my project when updating to react-native 0.54.2

Here are the errors : 
![image](https://user-images.githubusercontent.com/9078109/37458654-faef7da4-2845-11e8-92f6-cfed741bf672.png)

I am using last version :  "react-navigation-redux-helpers": "^1.0.3",

**Comment by Ashoat** [comment]
Try `flow-typed install`
