### ISSUE TITLE
lifecycle events aren't working with redux

### ISSUE THREAD

**Issue by DannyvanderJagt** [react-navigation/react-navigation-redux-helpers#20]
Hi all,

While working on our upgrade to the new `react-navigation@1.5.6` I noticed that the lifecycle events aren't working with `react-navigation-redux-helpers`. The same code does work without this library. 

I'm not sure if this is mentioned in this part of the documentation:
`Keep in mind that when a navigator is given a navigation prop, it relinquishes control of its internal state. That means you are now responsible for persisting its state, handling any deep linking, Handling the Hardware Back Button in Android, etc.` from [Redux integration documentation of react-navigation](https://reactnavigation.org/docs/redux-integration.html)

Incase it isn't, I created an [Expo Snack](https://snack.expo.io/@dannyvanderjagt/react-navigation-redux-helpers-lifecycle-events-not-working) to reproduce the issue. The snack is using the redux integration and the lifecycle events aren't firing. If you replace `<AppWithNavigationState/>` with `AppNavigator` then the lifecycle events do work.

After doing some debugging on my own and digging into the source code of both `react-navigation` and `react-navigation-redux-helpers` I figured out that the events and there handlers are registered but never fired. Incase this is a new issue that needs to be fixed I will more then glad to help.

[Lifecycle documentation](https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle)
[Expo Snack](https://snack.expo.io/@dannyvanderjagt/react-navigation-redux-helpers-lifecycle-events-not-working)

Let me know what you people think.

**Comment by psyanite** [comment]
Related??? https://github.com/react-navigation/react-navigation-redux-helpers/issues/51
