### ISSUE TITLE
please publish the index.d.ts

### ISSUE THREAD

**Issue by tangzhen** [react-navigation/react-navigation-redux-helpers#22]
I saw the pull request "https://github.com/react-navigation/react-navigation-redux-helpers/pull/17" already merged and publish the new version 1.0.4, but the problem is v1.0.4 doesn't include the "index.d.ts", so we still have an error when using the typescript, please help to fix it.

**Comment by Ashoat** [comment]
Oops! Thanks for the report, this should be fixed now.
