### ISSUE TITLE
Active tab in TabNavigator

### ISSUE THREAD

**Issue by crobinson42** [react-navigation/react-navigation-redux-helpers#24]
I am using redux integration in a very simple fashion.

### Current Behavior
Using TabNavigator a user touches a tab to navigate to it - the redux reducer returns no state change so the the `screen` does not change:
```
// navigation redux reducer snippet...

[NavigationActions.NAVIGATE]: (state, action) => {
    const newState = AppNavigation.router.getStateForAction(
      action,
      state
    );

    newState.currentRoute = getCurrentRoute(newState).routeName;
    
    // return newState;
   // temporary: stop the screen from changing so return the same state
   return state;
  }

...
```
The screen DOES NOT change, however, the "active" tab DOES change to the tab that the user touched which is indicated by changing to the `activeIcon` specified in `TabNavigatorConfig.tabBarOptions.tabs`.

### Expected Behavior
The "active" tab should remain the same as the current `screen`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.3
| node             | 8
| npm or yarn      | yarn

**Comment by Ashoat** [comment]
I don’t think overriding the default reducer behavior is supported in react-navigation. As far as I understand, there is state outside of the Redux store that gets changed when you navigate. If that’s not it, it might be some of the other actions that occur on navigation (maybe the `COMPLETE_TRANSITION` one?).

**Comment by crobinson42** [comment]
Interesting - I put a custom redux middleware function in and returned null on `COMPLETE_TRANSITION` actions but the active tab transition still occurs. I don't see any other `NAVIGATION/*` actions coming through during the tab nav action.

How would you prevent a user from going to a different tab in the TabNavigator based on some validation (or user input confirmation)?

**Comment by Ashoat** [comment]
`tabBarOnPress` should work for you.

**Comment by Ashoat** [comment]
https://reactnavigation.org/docs/tab-navigator.html

**Comment by crobinson42** [comment]
Just an update for anyone who finds this issue, my problem was related to using `tabBarComponent: ...` with this library: https://github.com/timomeh/react-native-material-bottom-navigation#bottomnavigation
