### ISSUE TITLE
Make it compatible with react-navigation 2.0.0

### ISSUE THREAD

**Issue by niteshgrg** [react-navigation/react-navigation-redux-helpers#29]
├── UNMET PEER DEPENDENCY react-navigation@2.0.0
└── react-navigation-redux-helpers@1.0.6

**Comment by sjkyspa** [comment]
any updates about this？

**Comment by Ashoat** [comment]
Taking a look now. I think `addNavigationHelpers` has been deprecated in `react-navigation@2`, so changes will be necessary.

**Comment by MrLoh** [comment]
Not really, it has just been removed, I am using this with react navigation 2.0.1 without any issues.

**Comment by Ashoat** [comment]
Should be good now.

**Comment by MrLoh** [comment]
I’m having an issue with redux integration at the moment. Trying to dig through the source code to understand who the listener differs in the normal vs the redux case. Could it have something to do with changes here?
https://github.com/react-navigation/react-navigation/issues/4244

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
