### ISSUE TITLE
Typescript definitions not updated

### ISSUE THREAD

**Issue by jbrodriguez** [react-navigation/react-navigation-redux-helpers#3]
I'd like to say that I feel the jump to 1.0.0 stable was rushed.

As for the bug

```js
Argument of type '{ dispatch: NavigationDispatch<any>; state: NavigationState; addListener: any; }' is not assignable to parameter of type 'NavigationProp<NavigationState, NavigationStackAction>'.
  Object literal may only specify known properties, and 'addListener' does not exist in type 'NavigationProp<NavigationState, NavigationStackAction>'.
```

comes from 

```js
<Navigator
  navigation={addNavigationHelpers({
	dispatch: this.props.dispatch as NavigationDispatch<any>,
	state: this.props.nav,
	addListener,
  })}
/>
```

since https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-navigation/index.d.ts isn't up to date.

Since I create the store in a separate file from the creation of the Navigator, I had to define an instance property (this.addListener), so that it's created after the redux middleware.

**Comment by Ashoat** [comment]
It seems like this issue has to do with `react-navigation` as a whole, rather with the Redux integration specifically. Please post this issue on the main `react-navigation` issue tracker so it can get the appropriate eyeballs. I maintain the Flow types for `react-navigation` btw so have some thoughts, feel free to tag me in the post! :)
