### ISSUE TITLE
Use releases and help the community with breaking changes

### ISSUE THREAD

**Issue by yordis** [react-navigation/react-navigation-redux-helpers#35]
Hey mates,

I noticed that all my code is broken because of the `react-navigation@2` which is fine but I went to Release tab over here on Github for read about the release but I didn't find any release on this package.

I know the documentation was updated but it would be nice if you could use the Release documentation for help the community to understand what changed and how to fix.

What do you think?

**Comment by Ashoat** [comment]
Okay, I'll do this in the future. For reference, `react-navigation-redux-helpers@1.0.7` is the last version that supports `react-navigation@1.x`.
