### ISSUE TITLE
getNavigation is undefined

### ISSUE THREAD

**Issue by eabait** [react-navigation/react-navigation-redux-helpers#41]
Hey guys

I'm trying to upgrade my app to `react-navigation 2.3.0` and `react-navigation-redux-helpers 2.0.1`. I'm getting the error `_reactNavigation.getNavigation` is undefined in line 139 of middleware.js.
Any ideas?

Thanks!
Esteban

**Comment by Ashoat** [comment]
I think you need `react-navigation@2.3.1` as a minimum. Let me know if that doesn’t solve your problem.

**Comment by eabait** [comment]
Indeed, that was the problem. Thanks @Ashoat

**Comment by askiiRobotics** [comment]
You should add this to guide on main page. It is not a clear problem.
