### ISSUE TITLE
(0 , _reactNavigationReduxHelpers.reduxifyNavigator) is not a function

### ISSUE THREAD

**Issue by slootmaekersdirk** [react-navigation/react-navigation-redux-helpers#57]
hello,

i have an issue with the above error:

i use : 

    "react-navigation": "2.4.0",
    "react-navigation-redux-helpers": "^2.0.0-beta.1",
 but the issues persists also with the 2.9.3 and 2.0.5 of the redux helpers. The example does not have the issue.

here is the code : 

import React, { Component } from "react";
import { connect } from "react-redux";
//import Root from "baseline/navigations/root";
//import { addListener } from "baseline/reducers/nav";
import { createReactNavigationReduxMiddleware } from "react-navigation-redux-helpers";
import { reduxifyNavigator } from "react-navigation-redux-helpers";
import LoginForm from "baseline/components/loginForm";
import { createStackNavigator } from "react-navigation";

/*
class AppNavigator extends Component {
  render() {
    const { dispatch, nav } = this.props;
    const navigation = navigationPropConstructor(dispatch, nav);
    return <Root navigation={navigation} />;
  }
}

export default connect(state => ({ nav: state.nav }))(AppNavigator);

*/

const navMiddleware = createReactNavigationReduxMiddleware(
  "root",
  state => state.nav
);

const RootNavigator = createStackNavigator({
  Unauthorized: {
    screen: LoginForm
  }
});

const AppWithNavigationState = reduxifyNavigator(RootNavigator, "root");

const mapStateToProps = state => ({
  state: state.nav
});

const AppNavigator = connect(mapStateToProps)(AppWithNavigationState);

export { AppNavigator, navMiddleware };

the code stops working with the following error:

Console was cleared
ExceptionsManager.js:76 (0 , _reactNavigationReduxHelpers.reduxifyNavigator) is not a function
handleException @ ExceptionsManager.js:76
handleError @ InitializeCore.js:69
reportFatalError @ error-guard.js:42
guardedLoadModule @ require.js:163
metroRequire @ require.js:152
(anonymous) @ notification.ios.js:69
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:65
RCTLog.js:47 Required dispatch_sync to load constants for RNDeviceInfo. This may lead to deadlocks
logToConsole @ RCTLog.js:47
logIfNoNativeHook @ RCTLog.js:30
__callFunction @ MessageQueue.js:344
(anonymous) @ MessageQueue.js:107
__guard @ MessageQueue.js:291
callFunctionReturnFlushedQueue @ MessageQueue.js:106
(anonymous) @ debuggerWorker.js:72
RCTLog.js:47 Running application GMO ({
    initialProps =     {
    };
    rootTag = 21;
})
ExceptionsManager.js:76 Module AppRegistry is not a registered callable module (calling runApplication)
handleException @ ExceptionsManager.js:76
handleError @ InitializeCore.js:69
reportFatalError @ error-guard.js:42
__guard @ MessageQueue.js:293
callFunctionReturnFlushedQueue @ MessageQueue.js:106
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:84 Unhandled JS Exception: (0 , _reactNavigationReduxHelpers.reduxifyNavigator) is not a function
reactConsoleErrorHandler @ ExceptionsManager.js:84
logToConsole @ RCTLog.js:47
logIfNoNativeHook @ RCTLog.js:30
__callFunction @ MessageQueue.js:344
(anonymous) @ MessageQueue.js:107
__guard @ MessageQueue.js:291
callFunctionReturnFlushedQueue @ MessageQueue.js:106
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:84 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)
reactConsoleErrorHandler @ ExceptionsManager.js:84
logToConsole @ RCTLog.js:47
logIfNoNativeHook @ RCTLog.js:30
__callFunction @ MessageQueue.js:344
(anonymous) @ MessageQueue.js:107
__guard @ MessageQueue.js:291
callFunctionReturnFlushedQueue @ MessageQueue.js:106
(anonymous) @ debuggerWorker.js:72

any ideas?

thanks
Dirk

**Comment by slootmaekersdirk** [comment]
FYI I'm using RN 0.56

**Comment by Ashoat** [comment]
> but the issues persists also with the 2.9.3 and 2.0.5 of the redux helpers.

This is where your issue is. `reduxifyNavigator` is not in `2.0.0-beta.1`, but it is in `2.0.5`. Something went wrong when you tried to install the newer version. You can confirm the version by checking `node_modules/react-navigation-redux-helpers/package.json`.

**Comment by tosikaz** [comment]
I have the same issue in any version(react-navigation & helpers).
please help me.

**Comment by dianbagus96** [comment]
@tosikaz  try to reset the cache npm with following command  npm start -- --reset-cache
worked well for me
