### ISSUE TITLE
 TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by Devid2727** [react-navigation/react-navigation-redux-helpers#59]
I am using Jest to write unit test cases, Just week ago my test cases was working properly, but from last two days i am getting one error. I havent done any changes, i dont understand why this coming and tried to find solution but didnt get any proper response.  Below i have added my error and configuration.

**Error**

>   ● Test suite failed to run
> 
>     TypeError: Cannot read property 'init' of undefined
>       
>       at Object.<anonymous> (node_modules/react-navigation-redux-helpers/src/reducer.js:1:306)
>       at Object.<anonymous> (node_modules/react-navigation-redux-helpers/src/middleware.js:1:366)
>       at Object.<anonymous> (node_modules/react-navigation-redux-helpers/src/index.js:1:419)

And In my package.json file 

```
 "react": "16.3.1",
 "react-native": "^0.55.4",
 "react-navigation": "^1.5.12",
 "react-navigation-redux-helpers": "^1.0.5",
  "react-redux": "^5.0.7",
   "redux-thunk": "^2.2.0",
```

I have also added 

```
 "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|native-base|rn-viewpager|react-navigation-redux-helpers|react-navigation)"
    ]
  }
```

Please let me know if anybody facing such issues or any one have got any solution to fix this.
Thanks

**Comment by Ashoat** [comment]
Some context in #23 for people who haven't seen it (@Devid2727, I know you have).

I'm not immediately sure what's going on exactly here. The error is on the import of `NavigationActions` from `react-navigation`, and your version of `react-navigation` is quite old, so my first thought is that maybe that version of `react-navigation` doesn't declare that export correctly. You could read the code in `node_modules/react-navigation` and see if you can find the export.

In general I'd suggest updating your versions of both `react-navigation` and `react-navigation-redux-helpers`.

If you can create a minimal repro using either Expo Snack or a clean `react-native init`'d repo, I can try and help debug the issue.

**Comment by MikhailVolkov350504** [comment]
Hi all. A faced the same issue after upgrade to **RN 0.57**

Adding `react-navigation-redux-helpers` in `transformIgnorePatterns` did not help.

My package.json
```{
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "babel-plugin-jest-hoist": "^23.2.0",
    "@babel/plugin-transform-block-scoping": "^7.0.0",
    "@babel/plugin-transform-flow-strip-types": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-transform-computed-properties": "^7.0.0",
    "@babel/plugin-transform-destructuring": "^7.0.0",
    "@babel/plugin-transform-function-name": "^7.1.0",
    "@babel/plugin-transform-literals": "^7.0.0",
    "@babel/plugin-transform-parameters": "^7.1.0",
    "@babel/plugin-transform-shorthand-properties": "^7.0.0",
    "@babel/plugin-transform-react-jsx": "^7.0.0",
    "@babel/plugin-transform-regenerator": "^7.0.0",
    "@babel/plugin-transform-sticky-regex": "^7.0.0",
    "@babel/plugin-transform-unicode-regex": "^7.0.0",
    "@babel/plugin-transform-modules-commonjs": "^7.1.0",
    "@babel/plugin-transform-classes": "^7.1.0",
    "@babel/plugin-transform-arrow-functions": "^7.0.0",
    "@babel/plugin-transform-spread": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-transform-template-literals": "^7.0.0",
    "@babel/plugin-transform-exponentiation-operator": "^7.1.0",
    "@babel/plugin-transform-object-assign": "^7.0.0",
    "@babel/plugin-transform-for-of": "^7.0.0",
    "@babel/plugin-transform-react-display-name": "^7.0.0",
    "@babel/plugin-transform-react-jsx-source": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "^0.45.6",
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-navigation": "2.9.1",
    "react-navigation-redux-helpers": "2.0.4",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-redux|react-navigation-redux-helpers)"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  }
}
```

And my .babelrc
```
{
  "presets": ["module:metro-react-native-babel-preset"]
}
```

**Comment by NachosSs** [comment]
Same problem here.
