### ISSUE TITLE
support react-navigation v3?

### ISSUE THREAD

**Issue by slorber** [react-navigation/react-navigation-redux-helpers#64]
Hi,

Just wondering if support for react-navigation v3 (currently in alpha) is planned for this repo?

As mentionned in the doc, there will be no official support for redux in v3. Just wonder if someone has started working on non-official support?

Also, if no support, will a migration path be recommended?

# My usecase

I'm the new maintainer of a legacy app, initially based on Ignite, that I migrated to Expo. It extensively uses redux-saga for all api calls and dispatching navigation actions (not my choice). I don't really care about keeping navigation state in Redux, but I don't necessarily want to rewrite all the async/navigation of my app to upgrade to the upcoming v3. 

I'm probably not alone in this case, navigating by dispatching redux actions, from a place where the navigation prop is not provided.

# possible solution 

Just to give some ideas, here is a possible migration path that I envision:

- Keep Redux and my sagas
- Use Redux as a simple event bus for navigation actions (like my [redux-dispatch-subscribe](https://github.com/slorber/redux-dispatch-subscribe).
- create a component that receive navigation prop, attach dispatch listener to redux, and forward redux navigation actions directly to the navigation.dispatch

The idea is to still be able to navigate by dispatching to redux (and thus from sagas), but do not keep navigation state inside redux, and instead forward the actions to the stateful navigation container directly. Hope this makes sense.

**Comment by Ashoat** [comment]
Hey @slorber! I think the "official support" thing doesn't actually reflect any changes to this package's relationship with React Navigation, but perhaps @ericvicenti or @brentvatne can correct me if I'm wrong. I have no plans to stop supporting this package.

Mostly I think they're just pretty frustrated with the volume of issue spam they get from people with Redux-specific problems, so they're gonna take down the docs page about Redux integration. They're already treating this package mostly as a third-party thing, even though it does exist within the React Navigation org.

I haven't yet gotten it working with React Navigation 3, and I'm not sure how hard it will be to get there. I tried upgrading my app once to a React Navigation 3 alpha release, and I had an issue where the entire screen was unresponsive. At the time I didn't have the bandwidth to investigate why.

**Comment by brentvatne** [comment]
> Hey @slorber! I think the "official support" thing doesn't actually reflect any changes to this package's relationship with React Navigation, but perhaps @ericvicenti or @brentvatne can correct me if I'm wrong. I have no plans to stop supporting this package.

correct!

> Mostly I think they're just pretty frustrated with the volume of issue spam they get from people with Redux-specific problems, so they're gonna take down the docs page about Redux integration. They're already treating this package mostly as a third-party thing, even though it does exist within the React Navigation org.

yup, this is mostly right. i'm happy to support an interface from react-navigation that enables redux and other libraries to work with it, i'm less excited about getting issue reports that involve redux, a handful of middleware and reducers, etc, and trying to debug what's wrong with someone's redux configuration rather than the react-navigation api surface area that enables it.

**Comment by Ashoat** [comment]
I just tried the latest version of this package with the current 3.0 RC and it works! Gonna close this issue, but if anybody experiences any issues let me know and I can reopen.

**Comment by ggdegreat** [comment]
doesn't worked for React Navigation v3.0

still encounter this issue:
https://github.com/react-navigation/react-navigation-redux-helpers/issues/63

my package.json
```

"dependencies": {
    "react": "^16.6.3",
    "react-native": "^0.57.8",
    "react-navigation": "^3.0.0-alpha.15",
    "react-navigation-redux-helpers": "^2.0.9",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-form": "^7.4.2",
    "redux-thunk": "^2.3.0",
  },
```

**Comment by Ashoat** [comment]
I can investigate further if you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.

**Comment by rullymartanto** [comment]
I Adding redux into my testig project it's work....
Not complete yet but I think its gonna work

import { Provider } from 'react-redux'
import { createStore, applyMiddleware } from 'redux'
import reducer from './reducers'
import thunk from 'redux-thunk'

import HomeTab from './Components/AppTabNavigator/HomeTab'
import SearchTab from './Components/AppTabNavigator/SearchTab'
import AddMediaTab from './Components/AppTabNavigator/AddMediaTab'
import LikesTab from './Components/AppTabNavigator/LikesTab'
import ProfileTab from './Components/AppTabNavigator/ProfileTab'

const middleware = [ thunk ];

const store = createStore(
  reducer,
  applyMiddleware(...middleware)
)

class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <AppContainer />
      </Provider>
    )
  }
}
export default App;

const DashboardTabNavigator = createBottomTabNavigator(
  {
    HomeTab,
    SearchTab,
    AddMediaTab,
    LikesTab,
    ProfileTab
  },
  {
    navigationOptions: ({ navigation }) => {
      return {
        headerLeft: <Icon name="camera" style={{ paddingLeft: 10 }} size={20} />,
        headerRight: <Icon style={{ paddingRight: 10 }} name="send" size={20} />,
        title: "Instagram",
      };
    }
  }
);
const AppNavigator = createStackNavigator(
  {
    Home: DashboardTabNavigator,
    // Details: DetailsScreen
  },
  {
    initialRouteName: "Home"
  }
);

const AppContainer = createAppContainer(AppNavigator);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
});
