### ISSUE TITLE
default namespaces

### ISSUE THREAD

**Issue by DerekPark** [react-navigation/react-navigation-redux-helpers#65]
I've noticed much of the initial setup has to do with simply assigning the "nav" and "root" namespace, I wonder if it would be beneficial to simply assign these by default, and use optional parameters to change these namespaces.  The purpose being much of the initial code, and sample, would be minimized for introductory users.

**Comment by Ashoat** [comment]
Good suggestion. PRs are welcome, and this one shouldn’t be hard to implement! Since it would require a breaking API change we could release it as 3.0.
