### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by vitorcamachoo** [react-navigation/react-navigation-redux-helpers#66]
After upgrading `react-navigation` to his latest version (2.18.0 => 3.0.2), I get the following error when navigating back from a tab router.

![screenshot 2018-11-28 at 15 40 10](https://user-images.githubusercontent.com/20595956/49163047-17e42500-f324-11e8-8d7a-58f9d56b3ff1.png)

**Comment by Ashoat** [comment]
Have you tried updating this package to the latest version?

**Comment by vitorcamachoo** [comment]
> Have you tried updating this package to the latest version?

Yes, i'm using `2.0.8`

**Comment by Ashoat** [comment]
I'm not able to repro this running `react-navigation@3.0.2` and `react-navigation-redux-helpers@2.0.8`. Navigating back from a `TabRouter` on Android should move you to the default route, and on iOS it should do nothing.

I can investigate further if you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.

**Comment by Ashoat** [comment]
Does this issue occur if you're not using `react-navigation-redux-helpers` and instead just using `react-navigation` directly?

Again - if you'd like me to investigate I'll need an MCVE.
