### ISSUE TITLE
Bad arguments on ReduxifyNavigator

### ISSUE THREAD

**Issue by maxime-aubry** [react-navigation/react-navigation-redux-helpers#67]
Here are my files :
[navigation/index.ts](https://github.com/maxime-aubry/StrongAndFit/blob/master/src/navigation/index.ts)
[navigation/routes.ts](https://github.com/maxime-aubry/StrongAndFit/blob/master/src/navigation/routes.ts)
[navigation/Reducers/index.ts](https://github.com/maxime-aubry/StrongAndFit/blob/master/src/navigation/Reducers/index.ts)

I have an error into navigation/index.ts on line 23. Sorry, it's in french.
Could you help me to understand what I have to do please ?
Thanks.

> L'argument de type 'ComponentType<{ state: NavigationState; dispatch: NavigationDispatch; }>' n'est pas attribuable au paramètre de type 'ComponentType<Matching<{ state: NavigationState; } & DispatchProp<AnyAction>, { state: NavigationState; dispatch: NavigationDispatch; }>>'.

> Impossible d'assigner le type 'ComponentClass<{ state: NavigationState; dispatch: NavigationDispatch; }, any>' au type 'ComponentType<Matching<{ state: NavigationState; } & DispatchProp<AnyAction>, { state: NavigationState; dispatch: NavigationDispatch; }>>'.
> 
> Impossible d'assigner le type 'ComponentClass<{ state: NavigationState; dispatch: NavigationDispatch; }, any>' au type 'ComponentClass<Matching<{ state: NavigationState; } & DispatchProp<AnyAction>, { state: NavigationState; dispatch: NavigationDispatch; }>, any>'.
> 
> Les types de la propriété 'propTypes' sont incompatibles.
> 
> Impossible d'assigner le type 'ValidationMap<{ state: NavigationState; dispatch: NavigationDispatch; }> | undefined' au type 'ValidationMap<Matching<{ state: NavigationState; } & DispatchProp<AnyAction>, { state: NavigationState; dispatch: NavigationDispatch; }>> | undefined'.
> 
> Impossible d'assigner le type 'ValidationMap<{ state: NavigationState; dispatch: NavigationDispatch; }>' au type 'ValidationMap<Matching<{ state: NavigationState; } & DispatchProp<AnyAction>, { state: NavigationState; dispatch: NavigationDispatch; }>>'.
> 
> Les types de la propriété 'dispatch' sont incompatibles.
> 
> Impossible d'assigner le type 'Validator<NavigationDispatch>' au type 'Validator<Dispatch<AnyAction>>'.
> 
> Impossible d'assigner le type 'NavigationDispatch' au type 'Dispatch<AnyAction>'. [2345]
> const App: React.ComponentType<{state: NavigationState; dispatch: NavigationDispatch;
> }>

**Comment by maxime-aubry** [comment]
Please, help.

**Comment by Ashoat** [comment]
I can investigate further if you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.
