### ISSUE TITLE
Nested TabNavigator Screen not rendering the first tab navigate 

### ISSUE THREAD

**Issue by toytonic** [react-navigation/react-navigation-redux-helpers#7]
This is a copy from https://github.com/react-navigation/react-navigation/issues/3604 as suggested by @brentvatne 

### Current Behavior

I have a the following structure with a nested tab navigator (main navigation) inside a stack navigator (for modals to 'popover'). Once managing the state via redux or mobx the first navigate (via tabbing) in the tab navigator to e.g. 'Tab2' is not rendered. After navigating back and forth it gets rendered. Using the same navigation structure but without redux/mobx works just fine.

```
export const MainNavigator = TabNavigator({
  Tab1: {screen: createScreen('tab1')},
  Tab2: {screen: createScreen('tab2')},
  Tab3: {screen: createScreen('tab3')}
})

export const AppNavigator = StackNavigator({
  Main: { screen: MainNavigator },
});
```

### Expected Behavior

Use a redux/mobx state management with the same behaviour as plain react navigation.

### How to reproduce
Here's a demo on expo:
https://snack.expo.io/@toytonic/react-navigation-nested-tabnavigator-redux

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.2.0 ( or latest master)
| react-native     | 0.52.0
| node             | 8
| npm or yarn      | 1.3.2

**Comment by brentvatne** [comment]
hi there! I will look into this tomorrow.

**Comment by zhouyingkai1** [comment]
I have the same problem

**Comment by Piropa** [comment]
I've had to revert to 1.03

**Comment by brentvatne** [comment]
there appears to be some bug with redux integration where the *first* action that happens in the app doesn't have the event properly dispatched.

to get around this for now you can add this to `componentWillMount` in your app somewhere: `this.props.navigation.navigate('THIS_PATH_DOES_NOT_EXIST');`

**Comment by brentvatne** [comment]
actually the above behavior is somewhat expected. notice that we have to do this in createNavigationContainer: https://github.com/react-navigation/react-navigation/blob/6785729fb5c13cd144f462f1ca07939f0753e65c/src/createNavigationContainer.js#L141-L159

@Ashoat - maybe we need to update redux docs?

**Comment by brentvatne** [comment]
@ericvicenti - pinging you because this is a bit awkward and curious if you have any thoughts on how to do it better

**Comment by nol13** [comment]
Posted this in referenced issue as well, but example of issue without using redux.

https://snack.expo.io/B1LdhUmdM

Steps to reproduce:

    click on search tab
    click on SavedSearch, screen is blank
    click back to NewSearch
    click on SavedSearch again, screen is not blank

**Comment by Ashoat** [comment]
Oh my god, this report has *exact* same typo as #3586.

Guys. The callback you pass to `createReactNavigationReduxMiddleware` has to select the navigation state from your Redux store. It can't select an undefined property.

I've considered warning in the case of an `undefined` property, but having the first action initialize state from `null` is a common Redux pattern (and one `react-navigation` uses).

**Comment by Ashoat** [comment]
Oops sorry that comment was meant for #10

**Comment by Ashoat** [comment]
Okay, so this is definitely a legit issue. Most use cases obscure the issue here by using something like `redux-persist`. Dispatching an `init` action on mount like Brent suggested above is a fine approach, though it does end up triggering the reducers twice. Since reducers are idempotent it doesn't matter, but I suppose it would be slightly better to only call the listeners, like the `createNavigationContainer.js` code does. I'll go ahead and add an export to this library to do just that.

**Comment by Ashoat** [comment]
I've published `react-navigation-redux-helpers@1.0.2` which includes a new exported function: `initializeListeners("root", navigationState)` which you can call from your App's `componentDidMount`. @toytonic feel free to reopen if that doesn't solve the issue.

**Comment by toytonic** [comment]
Thanks. Will verify it asap.

**Comment by toytonic** [comment]
@brentvatne @Ashoat Thanks for the update and the suggestions. It's working now. I am using mobx in my actual implementation. An update to the docs would definitely help others with similar issues.

Keep up the good work. Much appreciated!

**Comment by jacargentina** [comment]
@Ashoat I'm having the same issue; adding `initializeListeners` on my App's `componentDidMount` is not making my tab navigation work.

My app is here  https://github.com/jacargentina/iResucito, on branch `npm-updates`

**Comment by Ashoat** [comment]
@jacargentina please create a Snack with a minimal repro of your issue and I'll take a look!

**Comment by toytonic** [comment]
@jacargentina I had a similar setup as you.

Because of your initialization logic  in the App component `initializeListeners` in `componentDidMount` will be called before the MainStack will be rendered. You can create a separate component that only renders and initializes the MainStack to work around that issue.

**Comment by jacargentina** [comment]
@toytonic Thanks a lot! Was just like that.

**Comment by neeboo** [comment]
@toytonic Have you fixed the issue and how did you do it which mentioned by @jacargentina.
I still can't fixed my setup using `initializeListeners` in `componentDidMount`.

**Comment by azaabudeen** [comment]
Same issue...Any fix??

**Comment by toytonic** [comment]
Hi @neeboo as mentioned above I am using mobx with tsdi. But here is my basic implementation:

```
const navListener = createAddListener();

@observer
@external
export class Navigation extends React.Component<{}> {
    @inject private navStore!: NavigationStore;

    public componentDidMount(): void {
        this.navStore.dispatch(NavigationActions.init());
    }

    public render(): JSX.Element {
        return (
            <RootStack
                navigation={addNavigationHelpers({
                    dispatch: this.navStore.dispatch,
                    state: this.navStore.navigationState,
                    addListener: navListener
                })}
            />
        );
    }
}
```

**Comment by codesinghanoop** [comment]
I'm also facing this issue. I have added initializeListeners in componentDidMount where i declared the app navigation.
`componentDidMount () {
    initializeListeners('root', this.props.nav)
  }

  render () {
    return (
      <AppNavigation
        navigation={addNavigationHelpers({
          dispatch: this.props.dispatch,
          state: this.props.nav,
          addListener: createReduxBoundAddListener('root')
        })}
      />
    )
  }`

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
