### ISSUE TITLE
How can i get dispatch() from reduxifyNavigator with setTopLevelNavigator

### ISSUE THREAD

**Issue by ddthuan87** [react-navigation/react-navigation-redux-helpers#71]
Hi! Thank for the Lib!

**### Description ###**
I'm writing a GA tracking for my app.

Before adding GA, Im using "Navigating without the navigation prop" for top level app
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

> App.js
```
import Router from './app/config/routes';

export default class App extends Component {
    render() {
        return (
            <Provider store={store}>
                <Router 
                    ref={navigatorRef => {
                        NavigationService.setTopLevelNavigator(navigatorRef);
                    }}
                />
            </Provider>
        );
    }
}
```

With that, i got a setTopLevelNavigator (NavigationContainer dispatch() for all Navigation Service)

> ![screen shot 2018-12-20 at 10 25 44 am](https://user-images.githubusercontent.com/30521011/50262086-ee5d7b80-0441-11e9-828c-39cff2976f14.png)

### **### issue ###**
And now, im using reduxifyNavigator, i can not get a dispatch() setTopLevelNavigator for all navigation service

> routerWrapper.js
```
import { reduxifyNavigator } from 'react-navigation-redux-helpers';
import { connect } from 'react-redux';
import Router from '../config/routes';

const App = reduxifyNavigator(Router, "root");

const mapStateToProps = (state) => ({
    state: state.nav,
});
const AppWithNavigationState = connect(mapStateToProps)(App);

export default AppWithNavigationState;
```

> App.js
```
import WrapperRouter from './app/googleAnalytics/routerWrapper';

const store = getStore();

export default class App extends Component {
    render() {
        return (
            <Provider store={store}>
                <WrapperRouter 
                    ref={navigatorRef => {
                        console.log(navigatorRef);
                        NavigationService.setTopLevelNavigator(navigatorRef);
                    }}
                />
            </Provider>
        );
    }
}
```

> ![screen shot 2018-12-20 at 10 38 37 am](https://user-images.githubusercontent.com/30521011/50262362-76905080-0443-11e9-8ded-0520dab57583.png)

And last, react Navigation add Listener not working with reduxifyNavigator

```
componentDidMount(){
        this.props.navigation.addListener('willFocus', () => {
            this._handleDefaultLoad();
        });
    }
```

### SUMMARY
> **How can i get dispatch() from reduxifyNavigator set top level and react navigation add listener working**

**Comment by Ashoat** [comment]
I can investigate further if you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.

**Comment by ddthuan87** [comment]
> I can investigate further if you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.

OKAY, i will push it, thank for reply

**Comment by murrayee** [comment]
Hi, I have same issue ,How do you solve in the end？

**Comment by quyho-tnc** [comment]
Do you have any update?

**Comment by ddthuan87** [comment]
> Do you have any update?

mình không dùng nó nữa cậu ạ

**Comment by quyho-tnc** [comment]
Did you have another good solution?

**Comment by ddthuan87** [comment]
> Did you have another good solution?

are u using this lib for what?
