### ISSUE TITLE
I can't work with 3.0.0

### ISSUE THREAD

**Issue by LinMaris** [react-navigation/react-navigation-redux-helpers#75]
I can work with 2.0.9. By `reduxifyNavigator`

When I use `createReduxContainer` instead of `reduxifyNavigator`, I get an error.

![image](https://user-images.githubusercontent.com/17720805/52534925-d2f85800-2d82-11e9-91a5-921f7aec0e1c.png)

**Comment by antonjuls** [comment]
@LinMaris hey, notice that `createReactNavigationReduxMiddleware` take `key` as a second optional argument now. I just left a state as a first argument (and `root` key now is default) and it fixed the same issue for me.

**Comment by Ashoat** [comment]
Details about breaking changes can be found in the [releases tab](https://github.com/react-navigation/react-navigation-redux-helpers/releases/tag/3.0.0).

**Comment by LinMaris** [comment]
@antonjuls  @Ashoat That solved my problem.
Thanks

**Comment by SiJieMa** [comment]
![2019-02-11 2 40 17](https://user-images.githubusercontent.com/17939301/52548872-1696a480-2e0b-11e9-95fe-b1ffd9046446.png)
Adjusting the order of two parameters solves the problem
