### ISSUE TITLE
Problem with upgrading "react-navigation-redux-helpers" from 2.0.9 to 3.0.0

### ISSUE THREAD

**Issue by yeahecho** [react-navigation/react-navigation-redux-helpers#77]
![simulator screen shot - iphone x - 2019-02-24 at 16 50 13](https://user-images.githubusercontent.com/3847947/53306381-68531c00-385a-11e9-92f9-73bca736588d.png)
I replaced all the `reduxify-navigator` from code, uninstall & install react-navigation-redux-helpers, remove and install node_modules, reset my simulator, report is still there, any idea?

OS: macOS
"react": "16.6.3",
"react-native": "0.58.5",
"react-navigation": "^3.0.9",
"react-navigation-redux-helpers": "^3.0.0",
"react-redux": "^5.1.0",
 "redux": "^4.0.1",

**Comment by Ashoat** [comment]
It appears that something went wrong with the upgrade. Can you try deleting your `node_modules` folder and recreating it with either `npm install` or `yarn`?

**Comment by raen79** [comment]
I am having the same issue and deleting the `node_modules` folder does not solve it...

**Comment by Luis0Antonio** [comment]
Same issue here, I already deleted node_modules and install the modules again.

**Comment by hemmedo** [comment]
Same here...getting crazy with this can't find module reduxify-navigator error. There is no single reference to that function from my code anymore.

**Comment by Ashoat** [comment]
You guys are all having some code caching issue. Besides deleting `node_modules`, you can try `react-native start --reset-cache`.
