### ISSUE TITLE
Nav state is not PlainObject for redux preloadedState

### ISSUE THREAD

**Issue by sefatunckanat** [react-navigation/react-navigation-redux-helpers#79]
Initially i want to load my data but error when the react-navigation-redux-helpers 'nav' state prototype are not appropriate for the redux createStore

Redux Plain Controller
https://github.com/reduxjs/redux/blob/master/src/utils/isPlainObject.js
https://github.com/reduxjs/redux/blob/master/src/combineReducers.js#L36

Redux said, init state is required plain object or may be my fault

```
Loaded & Saved Data
{
"nav":{"key":"StackRouterRoot","isTransitioning":false,"index":0,"routes":[{"routeName":"Home","key":"id-1551559775480-0"}]},
"settings":{"currentTheme":"DARK","fullScreen":true}
}

const loadToLocal = async () => {
  try {
    const state = await AsyncStorage.getItem('STATE')
    if (state !== null) {
      return JSON.parse(state)
    } else {
      return undefined
    }
  } catch (ex) {
    console.error('Load Local Storage Error', ex)
    return undefined
  }
}

const store = createStore(
  appReducer,
  loadToLocal(),
  applyMiddleware(middleware)
)
store.subscribe(() => saveToLocal(store.getState()))
```
![image](https://user-images.githubusercontent.com/9070463/53687836-cc8a4a00-3d4a-11e9-83e6-8fd82e0dc66b.png)

**Comment by Ashoat** [comment]
The return type of your `loadToLocal` function is a `Promise`. You are passing a `Promise` as the first parameter to `createStore`.

**Comment by sefatunckanat** [comment]
Are you showing the right way? There was no explanatory answer.
