### ISSUE TITLE
I have a error when i use 3.0 ver

### ISSUE THREAD

**Issue by beingtyson** [react-navigation/react-navigation-redux-helpers#80]
```
import React from 'react';
import { BackHandler } from "react-native";
import { NavigationActions } from "react-navigation";
import { createReduxContainer,createReactNavigationReduxMiddleware } from 'react-navigation-redux-helpers';
import { Provider, connect } from 'react-redux';
import AppNavigation from './src/navigation'
import { createStore, applyMiddleware } from 'redux';
import AppReducer from './src/reducers'

const middleware = createReactNavigationReduxMiddleware(
  "root",
  state=>state.NavigationReducer
)

const App = createReduxContainer(AppNavigation, "root");
const mapStateToProps = (state) => ({
  state: state.NavigationReducer,
});
const AppWithNavigationState = connect(mapStateToProps)(App);


const store = createStore(
  AppReducer,
  applyMiddleware(
      middleware
  ),
);




// class ReduxNav extends React.Component {
//   componentDidMount() {
//     BackHandler.addEventListener("hardwareBackPress", this.onBackPress);
//   }

//   componentWillUnmount() {
//     BackHandler.removeEventListener("hardwareBackPress", this.onBackPress);
//   }

//   onBackPress = () => {
//     const { dispatch, nav } = this.props;
//     if (nav.index === 0) {
//       return false;
//     }

//     dispatch(NavigationActions.back());
//     return true;
//   };

//   render() {
//     /* more setup code here! this is not a runnable snippet */
//     return <App state={this.props.nav}  dispatch={this.props.dispatch} />;
//   }
// }
// const mapStateToProps = (state) => ({
//   nav: state.NavigationReducer
// });
// const RootNav = connect(mapStateToProps)(ReduxNav);

export default class Root extends Component {
  
  render() {
    
    return (
      <Provider store={store}>
        <AppWithNavigationState />
      </Provider>
    );
  }
}
```

when i build this code i can see 
Before calling 'createReduxContainer' , please call 'createReactNavigationReduxMiddleware'
why??

**Comment by beingtyson** [comment]
sorry my mistake.. i fixed it

**Comment by murrayee** [comment]
hi bro,i have the same issue ,How do you fix it

**Comment by beingtyson** [comment]
> hi bro,i have the same issue ,How do you fix it

`import React,{Component} from 'react';
import { BackHandler } from "react-native";
import { NavigationActions } from "react-navigation";
import { createReduxContainer,createReactNavigationReduxMiddleware,createNavigationReducer } from 'react-navigation-redux-helpers';
import { Provider, connect } from 'react-redux';
import AppNavigation from './src/navigation'
import { createStore, applyMiddleware } from 'redux';
import AppReducer from './src/reducers'
import { createLogger } from 'redux-logger';
import ReduxThunk from 'redux-thunk'

const middleware = createReactNavigationReduxMiddleware(
  state=>state.NavigationReducer
)
const logger = createLogger();

const App = createReduxContainer(AppNavigation);

const store = createStore(
  AppReducer,
  applyMiddleware(
      ReduxThunk,
      middleware,
      // logger,
    
  ),
);

class ReduxNav extends Component {
  componentDidMount() {
    BackHandler.addEventListener("hardwareBackPress", this.onBackPress);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener("hardwareBackPress", this.onBackPress);
  }

  onBackPress = () => {
    const { dispatch, NavigationReducer } = this.props;
    if (NavigationReducer.index === 0) {
      return false;
    }

    dispatch(NavigationActions.back());
    return true;
  };
  render(){
    return <App state={this.props.NavigationReducer} dispatch={this.props.dispatch}/>;
  }
}
const mapStateToProps = (state) => ({
  NavigationReducer : state.NavigationReducer
})
const RootNav = connect(mapStateToProps)(ReduxNav)

export default class Root extends Component {
  render() {
    return (
      <Provider store={store}>
        <RootNav />
      </Provider>
    );
  }
}
`

navigation.js

`import React, { Component } from 'react';
import { View, Text, Button, StyleSheet, Image, ImageBackground,TouchableOpacity } from 'react-native';
import { createStackNavigator } from "react-navigation";
import LoginView from "../components/Login";
import RegisterView from "../components/Register";
import PasswordView from '../components/Password';
import { responsiveHeight, responsiveWidth, responsiveFontSize } from 'react-native-responsive-dimensions';


const navigator = createStackNavigator({
  Login: LoginView,
  Register : RegisterView,
  Password : PasswordView
  // Register: {
  //   screen: RegisterView,
  //   navigationOptions
  // }
},{
  defaultNavigationOptions:{
    headerTitleStyle : {
            fontSize:responsiveFontSize(0.7),
            textAlign: "center",
            flex: 1,
            fontFamily: "AppleSDGothicNeo",
          },
          headerStyle : {
            backgroundColor: '#fff', 
            elevation:0
          },
          headerLeft: (
            <TouchableOpacity onPress={() => navigation.goBack(null)}>
                <Image source={require('../images/left_icon.png')} style={{marginLeft: 30,width:35,width:35,resizeMode:'contain'}}/>
            </TouchableOpacity>
          ),
  },
  initialRouteName: 'Password'
});


export default navigator;
`

**Comment by murrayee** [comment]
![image](https://user-images.githubusercontent.com/20828177/54340702-ed1fa180-4672-11e9-96b8-adf61eb35d56.png)

thx, the switch of the two parameters solves it !     T_T

**Comment by beingtyson** [comment]
> ![image](https://user-images.githubusercontent.com/20828177/54340702-ed1fa180-4672-11e9-96b8-adf61eb35d56.png)
> 
> thx, the switch of the two parameters solves it ! T_T

    "react-navigation": "^3.3.2",
    "react-navigation-redux-helpers": "^3.0.0",

**Comment by murrayee** [comment]
![image](https://user-images.githubusercontent.com/20828177/54341382-c498a700-4674-11e9-98bb-2c27f223c8fc.png)

**Comment by beingtyson** [comment]
so.. what is your problem?
